---
title: "Visualizations"
format: html
---

```{r}
library(ggplot2)
library(dplyr)
library(readr)
data <- read_csv("Voter_Registry_clean.csv")
```

```{r}
ggplot(data = data, aes(x = PARTY)) + geom_bar()
```

# take out the year of voter reg date in order to create visualization
```{r}
library(lubridate)
data$year_vote <- year(data$`VOTER REG DATE`)
```

# create the database for the first visualization
```{r}
data_vis1 <- data |>
  filter(year_vote >= 1990) |>
  filter(is.na(`STREET NAME`))
```

# create a barplot
```{r}
ggplot(data = data_vis1, aes(x = as.factor(year_vote), fill = PARTY), color = "black") +
  geom_bar() +
  scale_fill_manual(values = c("royalblue", "limegreen", "yellow2", "red3", "snow3"))+
  labs(title = "What happened in 2002 and 2003 with people registered to vote?",
       x = "Years",
       y = "Number of people volting",
       fill = "Party") +
  theme_minimal()
```

# try to prove that registration dates did not seem to correspond to the dates of birth listed - not used

```{r}
data$year_birth <- year(data$DOB)
```

```{r}
plot_year1 <- ggplot(data = data, aes(x = as.factor(year_birth))) + geom_bar()
```

```{r}
plot_year2 <- ggplot(data = data, aes(x = as.factor(year_vote))) + geom_bar()
```

```{r}
library(patchwork)
combined_year <- plot_year1 + plot_year2
combined_year
```
This is not working!

# Another way

```{r}
data_vis2 <- data |>
  mutate(years_old_vote = year_vote - year_birth) |>
  filter(years_old_vote <= 17) |>
  mutate(status = case_when(years_old_vote < 0 ~ "Impossible",
                            years_old_vote >= 0 & years_old_vote <= 17 ~ "Illegal",
                            TRUE ~ "Legal"))
```

```{r}
ggplot(data = data_vis2, aes(x = as.factor(years_old_vote), fill = status)) + 
  geom_bar() + 
  labs(title = "At what age are people registered to vote?",
       x = "Age when people are registered to vote",
       y = "Number of people",
       fill = "Voting Status") +
  geom_text(stat = 'count', aes(label = after_stat(count)), vjust = -0.5) +
  theme_minimal() +
  scale_fill_manual(values = c("red3", "snow4"))
```

# Timeline - not used
```{r, echo = FALSE}
library(timevis)
timeline_data <- data.frame(
  id      = 1:21,
  content = c("Investigation into Swiss VonRyker Institute", 
              "<b>VonRyker closes<b>", 
              "<b>First BSE case discovered at Mabton Farms<b>", 
              "<b>Phone calls between City Hall & Swiss number</b>", 
              "<b>Mayor Rex Luthor announced Boynton Labs development</b>", 
              "Breaking ground on Boynton Labs",
              "Voter registry fraud",
              "John Torch announces mayoral run",
              "Gov chose Boynton Labs to test for BSE",
              "US FDA investigation into Boynton Labs",
              "<b>Scandal! Torch seen with Boynton lab's Laurel Sulafate</b>",
              "US gov fighting initial BSE outbreak",
              "USDA killed 119 out of 129 Mabton & Alderwood cows",
              "FDA cancels investigation into Boynton labs",
              "Gov invests money in developing mad cow disease test",
              "Boynton labs breakthrough in BSE treatment",
              "<b>First phone call between City Hall & Swiss number</b>",
              "DNA evidence proves BSE positive cow is from Canada",
              "Scientists at Boynton labs produced prion protein",
              "<b>Washen Foundation</b> invests $1 mil in Boynton labs",
              "<b>Mayor Rex Luthor</b> announced Boynton Labs development"),
  start   = c("2001-08-30", 
              "2001-09-15", 
              "2001-12-01", 
              "2002-01-06", 
              "2002-02-02", 
              "2002-05-05",
              "2002-09-14",
              "2003-07-12",
              "2003-09-13",
              "2004-5-16",
              "2004-05-30",
              "2001-12-01",
              "2002-01-19",
              "2004-06-19",
              "2002-02-19",
              "2004-03-02",
              "2002-01-06",
              "2002-02-10",
              "2004-01-20",
              "2002-02-02",
              "2002-02-02"),
  end     = c("2001-09-15", 
              NA, 
              NA, 
              "2002-01-26", 
              NA, 
              NA,
              "2003-07-31",
              NA,
              NA,
              "2004-06-19",
              NA,
              "2002-02-20",
              NA,
              NA,
              NA,
              NA,
              NA,
              NA,
              NA,
              NA,
              NA),
  group = c("labs", 
            "labs", 
            "bse", 
            "pol", 
            "labs", 
            "labs", 
            "pol", 
            "pol", 
            "bse", 
            "labs", 
            "pol", 
            "bse", 
            "bse", 
            "labs", 
            "bse", 
            "labs",
            "pol", 
            "bse",
            "labs",
            "pol",
            "pol"),
  type = c("range", "point", "point", "range", "point", "point", "range", "point", "point", "range", "point", "range", "point", "point", "point", "point", "point","point", "point", "point","point")
)

groups <- data.frame(id = c("pol", "bse", "labs"),
                     content = c("Political", "Mad Cow Disease", "Lab News"))

timevis(timeline_data, groups = groups, options = list(editable = FALSE, selectable = FALSE, zoomable = F, stack = TRUE, verticalscroll = TRUE))
```
